#!/usr/bin/env python3
# tests/fixtures/generate_fixtures.py
#
# Generates the CSV review copies of the characterization fixtures from the
# SAME formulas as tests/fixtures/FixtureData.cs (the canonical source).
# Run:  python3 tests/fixtures/generate_fixtures.py   (from repo root or anywhere)
#
# IMPORTANT: keep this script in lockstep with FixtureData.cs:
#   - 32-bit LCG: state = (state * 1664525 + 1013904223) mod 2^32, seed 123456789
#   - Noise(amp) = ((state % 2000) / 1000.0 - 1.0) * amp
#   - identical draw order per fixture
# Known deviation: math.sin / System.Math.Sin may differ in the last ulp on
# some platform library pairs; this only affects large_dataset.csv cosmetic
# review, not the C# suite (which never reads CSVs).
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))


class Lcg(object):
    def __init__(self):
        self.state = 123456789

    def next(self):
        self.state = (self.state * 1664525 + 1013904223) & 0xFFFFFFFF
        return self.state

    def noise(self, amp):
        return ((self.next() % 2000) / 1000.0 - 1.0) * amp


def shuffled(lcg, pts):
    out = list(pts)
    for i in range(len(out) - 1, 0, -1):
        j = lcg.next() % (i + 1)
        out[i], out[j] = out[j], out[i]
    return out


def ordinary_section():
    lcg = Lcg()
    pts = []
    for i in range(41):
        x = i * 0.5
        pts.append((x, 100.0 + 0.02 * x + lcg.noise(0.03)))
    return shuffled(lcg, pts)


def profile_break_section():
    lcg = Lcg()
    pts = []
    for i in range(33):
        x = i * 0.25
        pts.append((x, 10.0 + 0.5 * x + lcg.noise(0.03)))
    for i in range(1, 33):
        x = 8.0 + i * 0.25
        pts.append((x, 14.0 + 0.1 * (x - 8.0) + lcg.noise(0.03)))
    return pts


def curb_section():
    lcg = Lcg()
    pts = []
    for i in range(33):
        pts.append((i * 0.25, 10.0 + lcg.noise(0.03)))
    for i in range(1, 4):
        pts.append((8.0 + i * 0.25, 10.0 + i * (0.4 / 3.0) + lcg.noise(0.03)))
    for i in range(29):
        x = 9.0 + i * 0.25
        pts.append((x, 10.4 + 0.01 * (x - 9.0) + lcg.noise(0.03)))
    return pts


def duplicate_xy_section():
    lcg = Lcg()
    pts = []
    for i in range(21):
        x = i * 0.5
        pts.append((x, 50.0 + 0.05 * x + lcg.noise(0.03)))
        if i == 4:
            pts.append((x, pts[-1][1]))
            pts.append((x, pts[-1][1]))
        if i == 10:
            pts.append((x, 53.0))
            pts.append((x, 56.5))
        if i == 15:
            pts.append((x, pts[-1][1]))
    return pts


def negative_coordinates_section():
    lcg = Lcg()
    pts = []
    for i in range(41):
        x = -1000.0 + i * 0.5
        pts.append((x, -5.0 + 0.01 * x + lcg.noise(0.03)))
    return shuffled(lcg, pts)


def large_section():
    lcg = Lcg()
    pts = []
    for i in range(20000):
        x = i * 0.001
        if 10.0 < x < 10.5:
            continue
        z = 100.0 + 0.5 * math.sin(x / 3.0) + 0.02 * x + lcg.noise(0.03)
        if 4.0 <= x < 4.3:
            z += 4.5
        if 12.0 <= x < 12.1:
            z += 8.0
        if 15.0 <= x < 15.1:
            z += 8.0 * (x - 15.0)
        if x >= 15.1:
            z += 0.8
        pts.append((x, z))
    return pts


def duplicate_xy_world_points():
    # Fixture 8 of FixtureData.cs (world space, intensity in 4th column).
    return [
        (10.0, 20.0, 100.0, 1.0),
        (10.0, 20.0, 103.5, 1.0),
        (10.0, 20.0, 105.0, 1.0),
        (-500.25, -1000.75, 7.0, 1.0),
        (-500.25, -1000.75, 7.0, 1.0),
        (0.0009999, 0.0, 3.0, 1.0),
        (0.0005, 0.0, 1.0, 1.0),
        (0.0015, 0.0, 2.0, 1.0),
        (4294967.296, 0.0, 5.0, 1.0),
        (4294967.297, 0.0, 6.0, 1.0),
    ]


def write_csv(name, header, rows):
    path = os.path.join(HERE, name)
    with open(path, "w", newline="\n") as f:
        f.write("# generated by tests/fixtures/generate_fixtures.py — review copy;\n")
        f.write("# canonical source: tests/fixtures/FixtureData.cs\n")
        f.write(header + "\n")
        for row in rows:
            f.write(",".join(repr(float(v)) for v in row) + "\n")
    print("wrote %s (%d rows)" % (name, len(rows)))


def main():
    write_csv("ordinary_section.csv", "x_along_m,elev_m", ordinary_section())
    write_csv("profile_break.csv", "x_along_m,elev_m", profile_break_section())
    write_csv("curb_section.csv", "x_along_m,elev_m", curb_section())
    write_csv("duplicate_xy_section.csv", "x_along_m,elev_m", duplicate_xy_section())
    write_csv("negative_coords.csv", "x_along_m,elev_m", negative_coordinates_section())
    write_csv("large_dataset.csv", "x_along_m,elev_m", large_section())
    write_csv("empty_cloud.csv", "x_along_m,elev_m", [])
    write_csv("duplicate_xy_world.csv", "x_m,y_m,z_m,intensity", duplicate_xy_world_points())


if __name__ == "__main__":
    main()
