"""Generate the native bridge's compile-time schema from PluginSettings metadata."""
from pathlib import Path
import re,json,math,sys
root=Path(__file__).resolve().parents[1]
text=(root/'Automation/PluginSettings.cs').read_text(encoding='utf-8')
entries=text[text.index('private static readonly Entry[]'):text.index('private static Entry B')]
def number(value):
    return {'Double.MaxValue':sys.float_info.max,'Int32.MaxValue':2147483647,'Math.PI':math.pi}.get(value,float(value) if re.fullmatch(r'[\d.]+',value) else None)
properties={}
for m in re.finditer(r'([BNIA])\("([^"]+)",\s*"([^"]+)"(?:,\s*([^)]*))?\)',entries):
    kind,key,prop,args=m.groups(); args=args.split(', ') if args else []
    typ='boolean' if kind=='B' else 'integer' if kind=='I' or kind=='A' and args==['true'] else 'number'
    d={'type':typ,'description':f'RoboLas {prop}; persisted in Robur settings; applies to the next operation.'}
    if typ!='boolean':
        if kind=='A': lo,hi,exclusive=(1,2147483647,False) if typ=='integer' else (0,sys.float_info.max,True)
        else: lo,hi=number(args[0]),number(args[1]); exclusive=kind=='N' and args[2]=='true'
        d['exclusiveMinimum' if exclusive else 'minimum']=float(lo); d['maximum']=float(hi)
    properties[key]=d
assert len(properties)==33
properties['request_id']={'type':'string','minLength':1,'description':'Unique write request ID; replay limited to retained process history.'}
properties['expected_context']={'type':'string','minLength':64,'description':'Fingerprint from las_preflight; checked before execution.'}
schema={'type':'object','properties':properties,'additionalProperties':False,'minProperties':1}
literal=json.dumps(schema,ensure_ascii=False,separators=(',',':')).replace('"','""')
output='// Generated by tools/generate_mcp_settings_schema.py; source: Automation/PluginSettings.cs\nnamespace LAS_TERRAIN.Mcp { internal static class SettingsSchema { internal const string Patch = @"'+literal+'"; } }\n'
target=root/'Mcp/SettingsSchema.cs'
if '--check' in sys.argv:
    assert target.read_text(encoding='utf-8')==output,'MCP settings schema drift; regenerate'
else: target.write_text(output,encoding='utf-8')
print('Native MCP schema: 33 plugin settings and 2 harness fields; '+('verified' if '--check' in sys.argv else 'generated'))
